-- create tables
CREATE TABLE IF NOT EXISTS accounts  (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL CHECK (name <> ''),
    balance DECIMAL(15, 2) DEFAULT 0.00 CHECK (balance >= 0.00)
);

-- insert initial data
INSERT INTO accounts (name, balance) VALUES ('Alice', 1000);
INSERT INTO accounts (name, balance) VALUES ('Bob', 500);

BEGIN; -- Session A
BEGIN; -- Session B
UPDATE accounts SET balance = balance - 100 WHERE name = 'Alice'; -- Session A
UPDATE accounts SET balance = balance - 50 WHERE name = 'Bob'; -- Session B
UPDATE accounts SET balance = balance + 50 WHERE name = 'Alice'; -- Session B
UPDATE accounts SET balance = balance + 100 WHERE name = 'Bob'; -- Session A [40P01] ERROR: deadlock detected Detail:
-- Process 71 waits for ShareLock on transaction 749; blocked by process 79.
-- Process 79 waits for ShareLock on transaction 748; blocked by process 71. Hint: See server log for query details.
-- Where: while updating tuple (0,2) in relation "accounts"
