-- create tables
DROP TABLE IF EXISTS accounts;

CREATE TABLE IF NOT EXISTS accounts  (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL CHECK (name <> ''),
    balance DECIMAL(15, 2) DEFAULT 0.00 CHECK (balance >= 0.00),
    indexed_balance DECIMAL(15, 2) DEFAULT 0.00 CHECK (balance >= 0.00)
);

CREATE INDEX ON accounts (indexed_balance);

-- insert initial data
DO
$$
DECLARE
    balance DECIMAL(15, 2);
BEGIN
    FOR counter IN 1..1001 LOOP
        balance = random() * 1000;
        INSERT INTO accounts (name, balance, indexed_balance) VALUES ('Account Name ' || counter, balance, balance);
    END LOOP;
END;
$$;


-- queries
-- all rows
EXPLAIN SELECT * FROM accounts; -- seq scan, cost 0.00..19.01
SELECT relpages, reltuples FROM pg_class WHERE relname = 'accounts';


EXPLAIN SELECT * FROM accounts WHERE balance < 500; -- seq scan + filter, cost 0.00..21.51
EXPLAIN SELECT * FROM accounts WHERE balance = 494.64; -- seq scan + filter, cost 0.00..21.51
EXPLAIN SELECT * FROM accounts WHERE id < 500; -- seq scan + filter, cost 0.00..21.51
EXPLAIN SELECT * FROM accounts WHERE id = 900; -- index scan, cost 0.28..8.29
EXPLAIN SELECT * FROM accounts WHERE indexed_balance < 500; -- seq scan + filter, cost 0.00..21.51
EXPLAIN SELECT * FROM accounts WHERE indexed_balance = 494.64; -- index scan, cost 0.28..8.29

SELECT histogram_bounds FROM pg_stats WHERE tablename='accounts' AND attname='balance';
SELECT null_frac, n_distinct, most_common_vals, most_common_freqs FROM pg_stats WHERE tablename='accounts' AND attname='name';
SELECT * FROM pg_stats WHERE tablename='accounts';

SELECT * FROM pg_stats;


EXPLAIN SELECT * FROM accounts WHERE name = 'Account Name 1';
